export let videos = [
	{
		id: 1,
		name: "Fullstack Web Development",
		creator: "Academind",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/pkdgVYehiTE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB94ZomtAk8QMtMbrgWvwdx574MHA",
		description: "D",
		videoCode: "pkdgVYehiTE",
		likes: 0,
		comments: [],
	},
	{
		id: 2,
		name: "Procedural Animation",
		creator: "t3ssel8r",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/KPoeNZZ6H4s/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDTm6LQajkoE5jvp9V-tr6ddxNyHw",
		description: "D",
		videoCode: "KPoeNZZ6H4s",
		likes: 0,
		comments: [],
	},
	{
		id: 3,
		name: "My Hero Academia | Official Trailer",
		creator: "AnimeHype",
		thumbnail: "https://i.ytimg.com/vi/vwlulN6OPyw/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB-FXF5ZnbjKL5gtMdxMDOMvu7ZHw",
		description: "D",
		videoCode: "vwlulN6OPyw",
		views: 0,
		likes: 0,
		comments: [],
	},
	{
		id: 4,
		name: "Big O Notation",
		creator: "Reducible",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/Q_1M2JaijjQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBJxIihI3woDWmojdTKnfL9lE9AXQ",
		description: "D",
		videoCode: "Q_1M2JaijjQ",
		likes: 0,
		comments: [],
	},
	{
		id: 5,
		name: "Creo - Carnivores",
		creator: "Creo",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/qZSSJk6OHdA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDZ4qB5K3fvzHf-GJWS1sIiPQHhQw",
		description: "D",
		videoCode: "qZSSJk6OHdA",
		likes: 0,
		comments: [],
	},
	{
		id: 6,
		name: "Python Decorator Functions",
		creator: "mCoding",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/SXApHXsDe8I/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAl0_K9WohA2D0M3jLc49CUQ00-dw",
		description: "D",
		videoCode: "SXApHXsDe8I",
		likes: 0,
		comments: [],
	},
	{
		id: 7,
		name: "Fairy Tail: 100-Year Quest | Official Teaser",
		creator: "AniTube",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/qiUZXKcCNpA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAXCEp2vLmLnS_KSkikps80zMZj4Q",
		description: "D",
		videoCode: "qiUZXKcCNpA",
		likes: 0,
		comments: [],
	},
	{
		id: 8,
		name: "Web Scraping APIs",
		creator: "John Watson",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/DqtlR0y0suo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUoRjjgJemvniu8uAsyHRJbH-Qkg",
		description: "D",
		videoCode: "DqtlR0y0suo",
		likes: 0,
		comments: [],
	},
	{
		id: 9,
		name: "Seemingly Impossible Riddle",
		creator: "Veritasium",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/iSNsgj1OCLA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDTCzTes5nhCdf5ZeFE15z1eydO4Q",
		description: "D",
		videoCode: "iSNsgj1OCLA",
		likes: 0,
		comments: [],
	},
	{
		id: 10,
		name: "First Ever Player In Minecraft",
		creator: "TheMisterEpic",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/PsawtFK3WB4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBRl_FhY785JpgJ0PmnaWlOp0Qfng",
		description: "D",
		videoCode: "PsawtFK3WB4",
		likes: 0,
		comments: [],
	},
	{
		id: 11,
		name: "CSS3 Animation",
		creator: "Traversy Media",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/zHUpx90NerM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD81lAQu1WnjIGwRe9HAel4djxgtw",
		description: "D",
		videoCode: "zHUpx90NerM",
		likes: 0,
		comments: [],
	},
	{
		id: 12,
		name: "Touring A Floating House",
		creator: "Enes Plus",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/wHAZyUAnO-0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA5CnOgEO7hFyRbeiZqsnHOdBQ3sA",
		description: "D",
		videoCode: "wHAZyUAnO-0",
		likes: 0,
		comments: [],
	},
	{
		id: 13,
		name: "Node JS Rest API",
		creator: "Dev Ed",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/vjf774RKrLc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD3MvsrkUcObxof4Vet6p2PIIIpKw",
		description: "D",
		videoCode: "vjf774RKrLc",
		likes: 0,
		comments: [],
	},
	{
		id: 14,
		name: "Creo - Red Horizon",
		creator: "Creo",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/kmYgwc4QYhE/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB7U3kX6-NxOtNC6stoz5XgkwtUPQ",
		description: "D",
		videoCode: "kmYgwc4QYhE",
		likes: 0,
		comments: [],
	},
	{
		id: 15,
		name: "Aggresive Chess Openings",
		creator: "GothamChess",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/Ib8XaRKCAfo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDqKS3f7MNBD-K4BpIAIPjf1YA9JA",
		description: "D",
		videoCode: "Ib8XaRKCAfo",
		likes: 0,
		comments: [],
	},
	{
		id: 16,
		name: "Beginner Python Projects",
		creator: "Tech With Tim",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/DLn3jOsNRVE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB5jRMJSxmHXd6NwJZAOaXTPtzhYA",
		description: "D",
		videoCode: "DLn3jOsNRVE",
		likes: 0,
		comments: [],
	},
	{
		id: 17,
		name: "NBA Epic Moments",
		creator: "dime",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/CXLM08fZO5o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBQ9BmR0pJUIsKeVJz_7SOt_-FBuQ",
		description: "D",
		videoCode: "CXLM08fZO5o",
		likes: 0,
		comments: [],
	},
	{
		id: 18,
		name: "Express JS Full Course",
		creator: "freeCodeCamp.org",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/Oe421EPjeBE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDgCDSpAmDl1IAEM1sfyLP7oQ8g2g",
		description: "D",
		videoCode: "Oe421EPjeBE",
		likes: 0,
		comments: [],
	},
	{
		id: 19,
		name: "Optimistic Nihilism",
		creator: "Kurzgesagt - In A Nutshell",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/MBRqu0YOH14/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDN7_ERbJzhOEhVlvGm9QVyuZRWYQ",
		description: "D",
		videoCode: "MBRqu0YOH14",
		likes: 0,
		comments: [],
	},
	{
		id: 20,
		name: "Wayde Van Niekerk Just Made A Statement",
		creator: "Total Running Productions",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/9GWOamisyzg/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAtnLObTwWaRVvAs1cAMHukQvBzJg",
		description: "D",
		videoCode: "9GWOamisyzg",
		likes: 0,
		comments: [],
	},
	{
		id: 21,
		name: "Learn CSS Box Model",
		creator: "Web Dev Simplified",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/rIO5326FgPE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDxhd3UWweh3VFzyLarDYGzwWcYhw",
		description: "D",
		videoCode: "rIO5326FgPE",
		likes: 0,
		comments: [],
	},
	{
		id: 22,
		name: "This Circle Is In Vanilla Minecraft",
		creator: "Mysticat",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/3u65Dk1bqWg/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCqeZWWpD50FHenR7sP9uF80AY_CA",
		description: "D",
		videoCode: "3u65Dk1bqWg",
		likes: 0,
		comments: [],
	},
	{
		id: 23,
		name: "Async JS Crash Course",
		creator: "Traversy Mdeia",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/PoRJizFvM7s/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBuI84djecG8XSDiJ9RT0MxT01-rQ",
		description: "D",
		videoCode: "PoRJizFvM7s",
		likes: 0,
		comments: [],
	},
	{
		id: 24,
		name: "How Norway Got Insanely Rich",
		creator: "Casual Scholar",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/9Wq2S1b-HCs/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCG3qiTMzFwzRDgYRmdf4MyhlQJwg",
		description: "D",
		videoCode: "9Wq2S1b-HCs",
		likes: 0,
		comments: [],
	},
	{
		id: 25,
		name: "Punishing Beginner Mistakes",
		creator: "Eric Rosen",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/D2Gs5upS1AA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBiBQ7h7Ba7N07ArKqO88pos_TIkQ",
		description: "D",
		videoCode: "D2Gs5upS1AA",
		likes: 0,
		comments: [],
	},
	{
		id: 26,
		name: "The Tragedy Of Humanity's Greatest Achievement",
		creator: "Pursuit of Wonder",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/hUfI7y3T8K4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCLqDOjdtf0dZ5hckOD-4uGh_f0Cw",
		description: "D",
		videoCode: "hUfI7y3T8K4",
		likes: 0,
		comments: [],
	},
	{
		id: 27,
		name: "Learn Dynamic Module Imports",
		creator: "Web Dev Simplified",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/ddVm53j80vc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBBPRLc1xS4nqa0epbckT4gELyMyQ",
		description: "D",
		videoCode: "ddVm53j80vc",
		likes: 0,
		comments: [],
	},
	{
		id: 28,
		name: "Greedy Algorithms Tutorial",
		creator: "freeCodeCamp.org",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/bC7o8P_Ste4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD7dxwIkhn3CLMUZWFdAHeI0l1S_A",
		description: "D",
		videoCode: "bC7o8P_Ste4",
		likes: 0,
		comments: [],
	},
	{
		id: 29,
		name: "Turbulent Flow vs. Laminar Flow",
		creator: "Veritasium",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/5zI9sG3pjVU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCDe-5M0lXNZacYgTxmh1-ZtfUGBQ",
		description: "D",
		videoCode: "5zI9sG3pjVU",
		likes: 0,
		comments: [],
	},
	{
		id: 30,
		name: "Web Development In 2022",
		creator: "Traversy Media",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/EqzUcMzfV1w/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAup3YgMytqO1Vii4Myhwp4_wFZhQ",
		description: "D",
		videoCode: "EqzUcMzfV1w",
		likes: 0,
		comments: [],
	},
	{
		id: 31,
		name: "JavaScript ES6 Modules",
		creator: "The Codeholic",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/ananPWEdfDA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBiPl9OAocoXYXCdlMQVA51irI9bg",
		description: "D",
		videoCode: "ananPWEdfDA",
		likes: 0,
		comments: [],
	},
	{
		id: 32,
		name: "The Misfit of Demon King Academy | Official Trailer",
		creator: "AnimeHype",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/sn9Rufl_RIc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBQxSb98GNhVBenXlMM9CDqEKJQEQ",
		description: "D",
		videoCode: "sn9Rufl_RIc",
		likes: 0,
		comments: [],
	},
	{
		id: 33,
		name: "Python Full Course",
		creator: "Bro Code",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/XKHEtdqhLK8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAwiaYg15KmdfuYUhMbmDWXAoam8Q",
		description: "D",
		videoCode: "XKHEtdqhLK8",
		likes: 0,
		comments: [],
	},
	{
		id: 34,
		name: "Would You Take This Bet",
		creator: "Veritasium",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/vBX-KulgJ1o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDyJXNRHS0bOVmkKQETq2D4ojeONA",
		description: "D",
		videoCode: "vBX-KulgJ1o",
		likes: 0,
		comments: [],
	},
	{
		id: 35,
		name: "Javascript Neural Networks",
		creator: "freeCodeCamp.org",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/Rs_rAxEsAvI/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDotaQQ-V-DzldSz8ZT1NKk5t3TGg",
		description: "D",
		videoCode: "Rs_rAxEsAvI",
		likes: 0,
		comments: [],
	},
	{
		id: 36,
		name: "Calculate Square Roots In You Head",
		creator: "MindYourDecisions",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/I7TFYa1v9xI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAYjxKY8HB7bHa3HGFG_XUkjJBtCQ",
		description: "D",
		videoCode: "I7TFYa1v9xI",
		likes: 0,
		comments: [],
	},
	{
		id: 36,
		name: "Solo Leveling | Official Trailer",
		creator: "AniTV",
		views: 0,
		thumbnail: "https://i.ytimg.com/vi/_0G4fAvucIs/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCDXBkvH8StfJ1Yf5vbtQwnc-KClg",
		description: "D",
		videoCode: "_0G4fAvucIs",
		likes: 0,
		comments: [],
	},
];